### ISSUE TITLE
Chart re-rendering seems to be broken

### ISSUE THREAD

**Issue by DDtKey** [Billy-Sheppard/chart-js-rs#12]
I'd like to update the chart on an event, approach with creating new chart seems broken:

Second call to `render`/`render_mutate` doesn't update the chart and moreover, I noticed that `render` call hangs. I.e it won't never finished.

Additionally, introducing `update` method could be considered (https://www.chartjs.org/docs/latest/developers/updates.html)

**Comment by Billy-Sheppard** [comment]
Dayum, could you give me an example of your code? I've never had to use update as I repaint my chart as required but I can see how it would be useful.

Let me have a look into how feasible it is to add the update method :)

**Comment by DDtKey** [comment]
Sure, actually the code is open.
You can check this PR: https://github.com/DDtKey/exponential-buckets-explorer/pull/1

You can start with `trunk serve --open --features logging`

You can pay attention to the console log, after any change it will be triggered but not finished

**Comment by DDtKey** [comment]
In fact, second render call fails with:
```
Uncaught Error: Canvas is already in use. Chart with ID '0' must be destroyed before the canvas with ID 'buckets-chart' can be reused.
```

**Comment by Billy-Sheppard** [comment]
I'm working on a solution at the moment, I'll let you know when its ready for testing.

**Comment by DDtKey** [comment]
Not sure if it may help, but I actually did such local patch:

```diff
# body of `render_chart` js function
- var chart = new Chart(ctx, obj);
+    var chart = Chart.getChart(ctx);
+    if (chart) {
+        chart.data.datasets = v.data.datasets;
+        chart.options = v.options;
+        chart.update();
+    } else {
+        new Chart(ctx, obj);
+    }
```

And it covered my needs pretty well - it dynamically re-renders the chart without destroying and jumps, but likely you have better idea how to support this.

To make it more clear - draft PR: https://github.com/Billy-Sheppard/chart-js-rs/pull/13

**Comment by Billy-Sheppard** [comment]
Try checking out my code in #14 

If this solves your situation I'll merge it in.

**Comment by Billy-Sheppard** [comment]
I think this can be closed now.
