### ISSUE TITLE
`options.scales[scale].ticks.callback` option doesn't exist

### ISSUE THREAD

**Issue by tqwewe** [Billy-Sheppard/chart-js-rs#20]
The `callback` option doesn't exist in the Rust types on the `ScaleTicks` type.
I tried cloning down this repo, and adding it manually with `callback: FnWithArgs`, but when I try to set the callback with:
```rust
callback: FnWithArgs::new().arg("value").body("value"),
```
I get an error in JS:
<img width="830" alt="Screenshot 2024-03-05 at 4 37 46 pm" src="https://github.com/Billy-Sheppard/chart-js-rs/assets/16362377/b8875896-a029-40fe-8934-1ed91bc0b64e">

Any idea how to solve this error to send a callback from Rust to JS?

**Comment by tqwewe** [comment]
I got this working by adding to `Chart::rationalise_js`:
```rust
Object::values(Object::try_from(&get_path(&self.0, "options.scales").unwrap()).unwrap())
    .iter()
    .for_each(|scale| {
        let ticks = Reflect::get(&scale, &"ticks".into());
        if ticks.is_ok() {
            let ticks = ticks.unwrap();

            let callback = Reflect::get(&ticks, &"callback".into());
            if let Ok(callback) = callback {
                if callback == JsValue::UNDEFINED {
                    return;
                }
                Reflect::set(
                    &ticks,
                    &"callback".into(),
                    &serde_wasm_bindgen::from_value::<FnWithArgs>(callback)
                        .unwrap()
                        .build(),
                )
                .unwrap();
            }
        }
    });
```

**Comment by tascord** [comment]
Thank you for the Issue! I've added support for this into #21. :3
